# Generated by Django 6.0.8 on 2026-10-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overbae", "0014_dataset_imports"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="workshop_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataset",
            name="workshop_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataset",
            name="workshop_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["state", "workshop_started_at", "workshop_queued_at"],
                name="dataset_workshop_busy_idx",
                condition=models.Q(state__in=["diagnosing", "running"]),
            ),
        ),
    ]
